# Generated by Django 5.2.1 on 2025-05-26 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_basket',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_of_user', to='main.basket'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of_user', to='main.order'),
        ),
        migrations.AddField(
            model_name='in_order',
            name='prodcut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_of_order', to='main.product'),
        ),
        migrations.AddField(
            model_name='in_basket',
            name='prodcut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_of_user', to='main.product'),
        ),
    ]
